name: ROS2 Build Pipeline

on:
  push:
    branches:
      - main
      # - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.workflow }} / ${{ github.run_number }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up ROS2 environment
        run: |
          sudo apt update && sudo apt install software-properties-common lsb-release -y
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install curl -y
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install ros-humble-ros-base -y
          source /opt/ros/humble/setup.bash
          echo 'source ~/ROS-Robot-Exploration/install/setup.bash' >> ~/.bashrc

      - name: Install colcon
        run: |
          sudo apt update && sudo apt install python3-pip -y
          pip3 install -U colcon-common-extensions

      - name: Set up Husarian submodule
        run: |
          git submodule update --init --recursive
          sudo apt install python3-vcstool -y
          sh setup.sh

      - name: Build ROS2 project
        run: |
          colcon build --symlink-install

      - name: List output files
        run: |
          echo "Listing build output..."
          ls install/
